SELECT
    a.AUTHOR_ID,
    a.AUTHOR_NAME,
    b.CATEGORY,
    SUM(b.PRICE * bs.SALES) AS TOTAL_SALES
FROM BOOK b
LEFT JOIN BOOK_SALES bs
    ON b.BOOK_ID = bs.BOOK_ID
LEFT JOIN AUTHOR a
    ON b.AUTHOR_ID = a.AUTHOR_ID
WHERE bs.SALES_DATE >= '2022-01-01'
  AND bs.SALES_DATE <  '2022-02-01'
GROUP BY
    a.AUTHOR_ID,
    a.AUTHOR_NAME,
    b.CATEGORY
ORDER BY 
    a.AUTHOR_ID,
    b.CATEGORY DESC