-- 컬럼 : ITEM_ID, ITEM_NAME
-- 테이블 : ITEM_INFO, ITEM_TREE
-- JOIN KEY : USING(ITEM_ID)
-- 조건 : ROOT아이템일것(PARENT_ITEM_ID IS NULL)
-- 정렬 : ITEM_ID

SELECT
    ITEM_ID, 
    ITEM_NAME
FROM ITEM_INFO AS I
LEFT JOIN ITEM_TREE AS T
USING(ITEM_ID)
WHERE PARENT_ITEM_ID IS NULL
GROUP BY 
    ITEM_ID, 
    ITEM_NAME
ORDER BY ITEM_ID