-- 컬럼 : SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
-- 테이블 : ONLINE_SALE, OFFLINE_SALE (세로로 연결하는 UNION)
-- 조건 : 2022년 3월의 판매 데이터
-- 정렬 : 판매일 기준 오름차순, 상품ID기준 오름차순, 유저ID 기준 오름차순
SELECT
    DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
    PRODUCT_ID,
    USER_ID,
    SALES_AMOUNT
FROM (
    SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE
    UNION ALL
    SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE
) UA
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;
