-- 컬럼 : REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE
-- 테이블 : REST_INFO, REST_REVIEW
-- 조건 : 위치가 서울
-- 정렬 : 평균점수 기준 내림차순, 즐겨찾기수 기준 내림차순
SELECT
    REST_ID,
    REST_NAME,
    FOOD_TYPE,
    FAVORITES,
    ADDRESS,
    ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_INFO RI
JOIN REST_REVIEW RR
USING (REST_ID)
WHERE ADDRESS LIKE '서울%'
GROUP BY REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS
ORDER BY SCORE DESC, FAVORITES DESC