-- 컬럼 : 년(YEAR), 월(MONTH), 성별(GENDER), 회원수(USERS)
-- 테이블 : ONLINE_SALE, USER_INFO
-- USING KEY : USER_ID
-- 그룹 : 년,월,성별별로
-- 정렬 : 년,월,성별 오름차순
SELECT
    YEAR(OS.SALES_DATE)  AS YEAR,
    MONTH(OS.SALES_DATE) AS MONTH,
    GENDER,
    COUNT(DISTINCT OS.USER_ID) AS USERS
FROM ONLINE_SALE OS
JOIN USER_INFO UI
USING(USER_ID)
WHERE GENDER IS NOT NULL
GROUP BY
    YEAR,
    MONTH,
    GENDER
ORDER BY
    YEAR,
    MONTH,
    GENDER