-- 컬럼 : ANIMAL_ID, NAME
-- 테이블 : ANIMAL_INS, ANIMAL_OUTS
-- KEY : ANIMAL_ID
-- 조건 : 입양을 간 기록은 있는데, 보호소에 들어온 기록이 없는 동물
-- 정렬 : ANIMAL_ID 오름차순
SELECT
    ANIMAL_ID,
    O.NAME
FROM ANIMAL_OUTS AS O
LEFT JOIN ANIMAL_INS AS I
USING (ANIMAL_ID)
WHERE O.DATETIME IS NOT NULL
    AND I.DATETIME IS NULL
GROUP BY
    ANIMAL_ID,
    O.NAME
ORDER BY ANIMAL_ID