-- 컬럼 : FACTORY_ID, FACTORY_NAME, ADDRESS
-- 테이블 : FOOD_FACTORY
-- 조건 : 주소가 강원도
-- 정렬 : 공장ID 기준 오름차순
SELECT
    FACTORY_ID,
    FACTORY_NAME,
    ADDRESS
FROM FOOD_FACTORY
WHERE ADDRESS LIKE '%강원도%'
ORDER BY FACTORY_ID