-- 컬럼 : ID, SIZE
-- 테이블 : ECOLI_DATA
-- 정렬 : ID
SELECT
    ID,
    CASE 
        WHEN SIZE_OF_COLONY <= 100 THEN 'LOW'
        WHEN SIZE_OF_COLONY <= 1000 THEN 'MEDIUM'
        ELSE 'HIGH'
    END AS SIZE
FROM ECOLI_DATA