#컬럼 : NAME, DATETIME
#JOIN KEY : AI.ANIMAL_ID = AO.ANIMAL_ID
#조건 : 입양을 못 간 동물 AO.DATETIME IS NULL
#정렬 : 가장 오래 보호소에 있었던 동물 3마리, 보호시작일 순으로 조회
SELECT
    AI.NAME,
    AI.DATETIME
FROM ANIMAL_INS AS AI
LEFT JOIN ANIMAL_OUTS AS AO
ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AO.DATETIME IS NULL
GROUP BY 
    AI.NAME,
    AI.DATETIME
ORDER BY DATETIME 
LIMIT 3
