-- 컬럼 : DR_NAME, DR_ID, MCDP_CD, HIRE_YMD
-- 테이블 : DOCTOR
-- 조건 : MCDP_CD='CS'OR'GS'
-- 정렬 : HIRE_YMD DESC, DR_NAME ASC

SELECT
    DR_NAME,
    DR_ID,
    MCDP_CD,
    DATE_FORMAT(HIRE_YMD, '%Y-%m-%d') AS HIRE_YMD
FROM DOCTOR
WHERE MCDP_CD='CS'
    OR MCDP_CD='GS'
ORDER BY HIRE_YMD DESC, DR_NAME ASC