-- 컬럼 : MEMBER_ID, MEMBER_NAME, GENDER, DATE_OF_BIRTH
-- 테이블 : MEMBER_PROFILE
-- 조건 : 생일이 3월, 여성, 전화번호가 NOT NULL
-- 정렬 : 회원ID 기준 오름차순
SELECT
    MEMBER_ID,
    MEMBER_NAME,
    GENDER,
    DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE DATE_FORMAT(DATE_OF_BIRTH, '%m') = '03'
  AND GENDER = 'W'
  AND TLNO IS NOT NULL
ORDER BY MEMBER_ID