-- 컬럼 : MEMBER_NAME, REVIEW_TEXT, REVIEW_DATE
-- 테이블 : MEMBER_PROFILE, REST_REVIEW
-- USING KEY : MEMBER_ID
SELECT
    MEMBER_NAME, 
    REVIEW_TEXT, 
    DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW R
JOIN MEMBER_PROFILE M
USING(MEMBER_ID)
WHERE MEMBER_ID=(
    SELECT
        MEMBER_ID
    FROM REST_REVIEW
    GROUP BY 
        MEMBER_ID
    ORDER BY
        COUNT(REVIEW_ID) DESC
    LIMIT 1
)
ORDER BY
    REVIEW_DATE, 
    REVIEW_TEXT
