-- 컬럼 : ANIMAL_ID, NAME
-- 테이블 : ANIMAL_INS, ANIMAL_OUTS
-- KEY : ANIMAL_ID
-- 조건 : 보호시작일보다 입양일이 더 빠른 동물
-- 정렬 : 보호시작일 빠른 순
SELECT
    ANIMAL_ID,
    I.NAME
FROM ANIMAL_INS AS I
LEFT JOIN ANIMAL_OUTS AS O
USING (ANIMAL_ID)
WHERE I.DATETIME > O.DATETIME
GROUP BY
    ANIMAL_ID,
    NAME
ORDER BY I.DATETIME