-- 컬럼 : FISH_COUNT
-- 테이블 : FISH_INFO, FISH_NAME_INFO
-- 조건 : FISH_NAME이 BASS와 SNAPPER
SELECT
    COUNT(*) AS FISH_COUNT
FROM FISH_INFO FI
JOIN FISH_NAME_INFO NI
USING (FISH_TYPE)
WHERE NI.FISH_NAME IN ('BASS', 'SNAPPER')