-- 컬럼 : FLAVOR
-- 조건 : TOTAL_ORDER >= 3,000 & INGREDIENT_TYPE='fruit_based'
-- 테이블 : FIRST_HALF, ICECREAM_INFO
-- 정렬 : 총주문량 기준, 내림차순
SELECT
    FLAVOR
FROM FIRST_HALF FH
JOIN ICECREAM_INFO II
USING (FLAVOR)
WHERE TOTAL_ORDER >= 3000 
    AND INGREDIENT_TYPE='fruit_based'
ORDER BY TOTAL_ORDER DESC