#테이블 : CAR_RENTAL_COMPANY_RENTAL_HISTORY, CAR_RENTAL_COMPANY_CAR
#JOIN KEY : H.CAR_ID = C.CAR_ID
#조건 : 자동차 종류가 '세단' AND 10월에 대여를 시작한 기록이 있음
#정렬 : 자동차ID 내림차순

SELECT DISTINCT
    H.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
LEFT JOIN CAR_RENTAL_COMPANY_CAR AS C
    ON H.CAR_ID = C.CAR_ID
WHERE C.CAR_TYPE = '세단'
  AND EXTRACT(MONTH FROM H.START_DATE) = 10
ORDER BY H.CAR_ID DESC
