-- 문제 : 2022년도 한해 평가 점수가 가장 높은 사원 정보를 조회
-- 컬럼 : SCORE	EMP_NO	EMP_NAME	POSITION	EMAIL
-- 테이블 : HR_EMPLOYEES, HR_DEPARTMENT(DEPT_ID), HR_GRADE(EMP_NO)
-- 정렬 : 평가점수 기준 내림차순 상위1개
SELECT
    SUM(SCORE) AS SCORE,
    EMP_NO,
    EMP_NAME,
    POSITION,
    EMAIL
FROM HR_EMPLOYEES
JOIN HR_DEPARTMENT
USING (DEPT_ID)
JOIN HR_GRADE
USING (EMP_NO)
GROUP BY         
    EMP_NO,
    EMP_NAME,
    POSITION,
    EMAIL
ORDER BY SCORE DESC
LIMIT 1

