-- 문제 : 상반기 동안 각 아이스크림 성분 타입과 성분 타입에 대한 아이스크림의 총주문량
-- 컬럼 : INGREDIENT_TYPE, TOTAL_ORDER
-- 테이블 : FIRST_HALF, ICECREAM_INFO (key : FLAVOR)
-- 정렬 : 총주문량 오름차순
SELECT
    DISTINCT INGREDIENT_TYPE,
    SUM(TOTAL_ORDER) OVER (PARTITION BY INGREDIENT_TYPE) AS TOTAL_ORDER
FROM FIRST_HALF
JOIN ICECREAM_INFO
USING(FLAVOR)
ORDER BY TOTAL_ORDER