-- 컬럼 : TITLE, BOARD_ID, REPLY_ID, WRITER_ID, CONTENTS, CREATED_DATE
-- 테이블 : USED_GOODS_BOARD, USED_GOODS_REPLY
-- 조건 : 2022년 10월에 작성
-- 정렬 : 댓글 작성일 오름차순, 게시글 제목 오름차순
SELECT
    TITLE,
    UR.BOARD_ID,
    UR.REPLY_ID,
    UR.WRITER_ID,
    UR.CONTENTS,
    DATE_FORMAT(UR.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD UB
JOIN USED_GOODS_REPLY UR
USING (BOARD_ID)
WHERE DATE_FORMAT(UB.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY UR.CREATED_DATE, TITLE