-- 컬럼 : 부서ID, 영문 부서명, 평균 연봉(소숫점 첫째자리에서 반올림)
-- 테이블 : HR_EMPLOYEES, HR_DEPARTMENT
-- KEY : DEPT_ID
-- 정렬 : AVG_SAL DESC

SELECT
    DEPT_ID,
    DEPT_NAME_EN,
    ROUND(SUM(SUM_SAL/CNT),0) AS AVG_SAL
FROM(
    SELECT
        DEPT_ID,
        COUNT(EMP_NO) as CNT,
        SUM(SAL) AS SUM_SAL
    FROM HR_EMPLOYEES E
    JOIN HR_DEPARTMENT D
    USING(DEPT_ID)
    GROUP BY DEPT_ID
) s
JOIN HR_DEPARTMENT d
USING(DEPT_ID)
GROUP BY 
    DEPT_ID,
    DEPT_NAME_EN
ORDER BY AVG_SAL DESC
