WITH base AS(
    SELECT
        *,
        SUM(SALES) OVER(PARTITION BY CATEGORY) AS TOTAL_SALES
    FROM BOOK b
    JOIN BOOK_SALES s
    USING(BOOK_ID)
    WHERE SALES_DATE >= '2022-01-01' AND SALES_DATE <  '2022-02-01'
)
SELECT
    CATEGORY,
    TOTAL_SALES
FROM base
GROUP BY
    CATEGORY
ORDER BY CATEGORY ASC