SELECT
    CATEGORY,
    SUM(SALES) AS TOTAL_SALES
FROM BOOK
JOIN BOOK_SALES
USING (BOOK_ID)
WHERE SALES_DATE >= '2022-01-01'
  AND SALES_DATE <  '2022-02-01'
GROUP BY 
    CATEGORY
ORDER BY CATEGORY;
